version: 2.1

orbs:
  android: circleci/android@2.0.3
  codecov: codecov/codecov@5

jobs:
  build:
    executor:
      name: android/android-docker
      tag: "2024.01.1"  # Specify the required tag
    steps:
      - checkout
      - run:
          name: Install Ninja
          command: |
            sudo apt-get update
            sudo apt-get install -y ninja-build
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: 868e0b6b-373f-4c9f-93ee-050672c6b0c5
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file